# Generated by Django 3.1.2 on 2020-10-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interact', '0006_auto_20201022_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(blank=True, null=True, related_name='followers', to='Interact.Profile'),
        ),
    ]
