# Generated by Django 3.1.2 on 2020-10-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interact', '0007_auto_20201023_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uploads',
            field=models.ManyToManyField(blank=True, related_name='uploads', to='Interact.Uploads'),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='images',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='videos',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
